/**
 * @file error-handler.js
 * @description Centralized Express error-handling middleware for DispatchIQ.
 *
 * All application errors are normalized into one consistent response format.
 * Every error response includes the request identifier generated by the
 * request-id middleware so client reports, structured logs, and operational
 * diagnostics can be correlated to the originating HTTP request.
 *
 * Expected operational errors are returned without unnecessary server-error
 * logging. Unexpected failures are recorded through the centralized
 * structured logger while exposing only sanitized information to clients.
 *
 * This middleware must be registered last in the Express middleware chain.
 */

import { HTTP_STATUS } from '@dispatchiq/shared';

import { logger } from '../logger/index.js';
import { AppError } from '../utils/app-error.js';

/**
 * Determines whether an error was produced by Express's JSON body parser while
 * parsing malformed request content.
 *
 * @param {unknown} error Unknown thrown error.
 * @returns {boolean} True when the error represents malformed JSON.
 */
function isMalformedJsonError(error) {
  return (
    error instanceof SyntaxError &&
    'status' in error &&
    error.status === HTTP_STATUS.BAD_REQUEST &&
    'type' in error &&
    error.type === 'entity.parse.failed'
  );
}

/**
 * Resolves the request identifier associated with the current HTTP lifecycle.
 *
 * `req.requestId` is the primary source populated by request-id middleware.
 * The response-local value is retained as a defensive fallback.
 *
 * @param {import('express').Request} req Express request.
 * @param {import('express').Response} res Express response.
 * @returns {string | undefined} Current request identifier.
 */
function getRequestId(req, res) {
  return req.requestId ?? res.locals.requestId;
}

/**
 * Centralized Express error-handling middleware.
 *
 * Response format:
 *
 * {
 *   success: false,
 *   error: {
 *     code,
 *     message,
 *     requestId,
 *     details?
 *   }
 * }
 *
 * Operational application errors preserve their configured HTTP status,
 * machine-readable error code, and optional details. Unexpected failures are
 * logged internally with correlation metadata while clients receive only a
 * generic response that does not expose implementation details.
 *
 * @param {unknown} err Unknown thrown error.
 * @param {import('express').Request} req Express request.
 * @param {import('express').Response} res Express response.
 * @param {import('express').NextFunction} next Express next callback.
 * @returns {import('express').Response} JSON error response.
 */
// eslint-disable-next-line no-unused-vars
export function errorHandler(err, req, res, next) {
  const requestId = getRequestId(req, res);

  if (isMalformedJsonError(err)) {
    return res.status(HTTP_STATUS.BAD_REQUEST).json({
      success: false,
      error: {
        code: 'MALFORMED_JSON',
        message: 'Request body contains malformed JSON.',
        requestId,
      },
    });
  }

  if (err instanceof AppError && err.isOperational) {
    const body = {
      success: false,
      error: {
        code: err.code,
        message: err.message,
        requestId,
      },
    };

    if (err.details !== undefined) {
      body.error.details = err.details;
    }

    return res.status(err.statusCode).json(body);
  }

  /*
   * Unexpected failures are recorded through structured logging rather than
   * console output. Passing the Error object using Pino's conventional `err`
   * field enables stack trace and error serialization support.
   */
  logger.error(
    {
      err,
      requestId,
      method: req.method,
      path: req.originalUrl ?? req.url,
    },
    'Unhandled request error.',
  );

  return res.status(HTTP_STATUS.INTERNAL_SERVER_ERROR).json({
    success: false,
    error: {
      code: 'INTERNAL_SERVER_ERROR',
      message: 'An unexpected error occurred.',
      requestId,
    },
  });
}
